// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/maintenanceentryattachment"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// MaintenanceEntryAttachmentDelete is the builder for deleting a MaintenanceEntryAttachment entity.
type MaintenanceEntryAttachmentDelete struct {
	config
	hooks    []Hook
	mutation *MaintenanceEntryAttachmentMutation
}

// Where appends a list predicates to the MaintenanceEntryAttachmentDelete builder.
func (mead *MaintenanceEntryAttachmentDelete) Where(ps ...predicate.MaintenanceEntryAttachment) *MaintenanceEntryAttachmentDelete {
	mead.mutation.Where(ps...)
	return mead
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mead *MaintenanceEntryAttachmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mead.sqlExec, mead.mutation, mead.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mead *MaintenanceEntryAttachmentDelete) ExecX(ctx context.Context) int {
	n, err := mead.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mead *MaintenanceEntryAttachmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(maintenanceentryattachment.Table, sqlgraph.NewFieldSpec(maintenanceentryattachment.FieldID, field.TypeInt))
	if ps := mead.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mead.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mead.mutation.done = true
	return affected, err
}

// MaintenanceEntryAttachmentDeleteOne is the builder for deleting a single MaintenanceEntryAttachment entity.
type MaintenanceEntryAttachmentDeleteOne struct {
	mead *MaintenanceEntryAttachmentDelete
}

// Where appends a list predicates to the MaintenanceEntryAttachmentDelete builder.
func (meado *MaintenanceEntryAttachmentDeleteOne) Where(ps ...predicate.MaintenanceEntryAttachment) *MaintenanceEntryAttachmentDeleteOne {
	meado.mead.mutation.Where(ps...)
	return meado
}

// Exec executes the deletion query.
func (meado *MaintenanceEntryAttachmentDeleteOne) Exec(ctx context.Context) error {
	n, err := meado.mead.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{maintenanceentryattachment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (meado *MaintenanceEntryAttachmentDeleteOne) ExecX(ctx context.Context) {
	if err := meado.Exec(ctx); err != nil {
		panic(err)
	}
}
